services:
  python_app:
    build: 
      context: ../python_service
      dockerfile: pydockerfile  
    networks:
      - mdk
    ports:
      - "9999:9999"
    container_name: python_app

  online_server:
    build:
      context: .
      dockerfile: Dockerfile  
    image: inter
    networks:
      - mdk
    container_name: online_server
    environment:
      - service_port= 9999
      - target_server_IP= 10.191.7.16
      - target_server_service_port=10231
      - assistant_server_IP=10.191.7.16
      

networks:
  mdk:
    driver: host

   
