services:
  python_app:
    build: 
      context: ../python_service
      dockerfile: pydockerfile  
    networks:
      - mdk
    ports:
      - "9999:9999"
    container_name: python_app
    environment:
      - SERVICE_PORT=${SERVICE_PORT}

  online_server:
    build:
      context: .
      dockerfile: Dockerfile  
    image: inter
    networks:
      - mdk
    container_name: online_server
    environment:
      - SERVICE_PORT=${SERVICE_PORT}
      - TARGET_IP=${TARGET_IP}
      - TARGET_PORT=${TARGET_PORT}
      - ASSISTANT_IP=${ASSISTANT_IP}
      

networks:
  mdk:
    driver: host

   
